export class SupportedMachines {
  constructor() {
    this.machineList = {
      "1": {
        "title": "Sinclair ZX Spectrum 48k",
        "year": "1982",
        "country": "UK",
        "lang": "EN",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/48.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Sinclair",
        "style": "default"
      },
      "2": {
        "title": "Sinclair ZX Spectrum 48k",
        "year": "1982",
        "country": "UK",
        "lang": "ES",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/48-spanish.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Sinclair",
        "style": "default"
      },
      "3": {
        "title": "Sinclair ZX Spectrum 128k",
        "year": "1986",
        "country": "UK",
        "lang": "EN",
        "memory": "128",
        "tape": "tapeloaders\/tape_128.szx",
        "tape_usr0": "tapeloaders\/tape_128_usr0.szx",
        "rom0": "roms\/128-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/128-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Sinclair",
        "style": "default"
      },
      "4": {
        "title": "Sinclair ZX Spectrum 128k",
        "year": "1985",
        "country": "UK",
        "lang": "ES",
        "memory": "128",
        "tape": "tapeloaders\/tape_128.szx",
        "tape_usr0": "tapeloaders\/tape_128_usr0.szx",
        "rom0": "roms\/128-spanish-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/128-spanish-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Sinclair",
        "style": "default"
      },
      "5": {
        "title": "Sinclair ZX Spectrum +2 128k",
        "year": "1986",
        "country": "UK",
        "lang": "EN",
        "memory": "128",
        "tape": "tapeloaders\/tape_plus2.szx",
        "tape_usr0": "tapeloaders\/tape_plus2.szx",
        "rom0": "roms\/plus2-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/plus2-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Amstrad",
        "style": "default"
      },
      "6": {
        "title": "Sinclair ZX Spectrum +2 128k",
        "year": "1986",
        "country": "UK",
        "lang": "ES",
        "memory": "128",
        "tape": "tapeloaders\/tape_plus2.szx",
        "tape_usr0": "tapeloaders\/tape_plus2.szx",
        "rom0": "roms\/plus2-spanish-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/plus2-spanish-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Amstrad",
        "style": "default"
      },
      "7": {
        "title": "Sinclair ZX Spectrum +2 128k",
        "year": "1986",
        "country": "UK",
        "lang": "FR",
        "memory": "128",
        "tape": "tapeloaders\/tape_plus2.szx",
        "tape_usr0": "tapeloaders\/tape_plus2.szx",
        "rom0": "roms\/plus2-french-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/plus2-french-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Amstrad",
        "style": "default"
      },
      "8": {
        "title": "Pentagon 128k",
        "year": "1989",
        "country": "Russia",
        "lang": "EN",
        "memory": "128",
        "tape": "tapeloaders\/tape_pentagon.szx",
        "tape_usr0": "tapeloaders\/tape_pentagon_usr0.szx",
        "rom0": "roms\/pentagon-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/128-1.rom",
        "rom1_page" : 33,
        "rom2": "roms\/trdos.rom",
        "rom2_page" : 35,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Unknown",
        "style": "default"
      },
      "9": {
        "title": "Timex Computer TC2048 16k",
        "year": "1982",
        "country": "Portugal",
        "lang": "EN",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/tc2048.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Timex",
        "style": "timex"
      },
      "10": {
        "title": "Timex Computer TC2068 48k",
        "year": "1982",
        "country": "Portugal",
        "lang": "EN",
        "memory": "48",
        "tape": "tapeloaders\/tape_ts2068.szx",
        "tape_usr0": "tapeloaders\/tape_ts2068.szx",
        "rom0": "roms\/tc2068-0.rom",
        "rom0_page" : 32,
        "rom1": "roms\/tc2068-1.rom",
        "rom1_page" : 33,
        "rom2": false,
        "rom2_page" : null,
        "status" : false,
        "tapeable" : true,
        "manufacturer" : "Timex",
        "style": "timex"
      },
      "11": {
        "title": "Inves Spectrum + 48k",
        "year": "1986",
        "country": "Spain",
        "lang": "ES",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/48-inves.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Investronica",
        "style": "investronica"
      },
      "12": {
        "title": "Microdigital TK90X 48k",
        "year": "1985",
        "country": "Brazil",
        "lang": "EN",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/tk90x-1.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Microdigital",
        "style": "microdigital"
      },
      "13": {
        "title": "Microdigital TK95 48k",
        "year": "1986",
        "country": "Brazil",
        "lang": "EN",
        "memory": "48",
        "tape": "tapeloaders\/tape_48.szx",
        "tape_usr0": "tapeloaders\/tape_48.szx",
        "rom0": "roms\/tk95.rom",
        "rom0_page" : 34,
        "rom1": false,
        "rom1_page" : null,
        "rom2": false,
        "rom2_page" : null,
        "status" : true,
        "tapeable" : true,
        "manufacturer" : "Sinclair",
        "style": "microdigital"
      }
    };
  }
  getList() {
    return this.machineList;
  }
}
