export class SupportedMachines {
  constructor() {
    this.machineList = {
      '1': { // default hardware
        'model': 'ZX Spectrum',
        'year': '1982',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sinclair',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '2': {
        'model': 'ZX Spectrum',
        'year': '1982',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-spanish.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sinclair',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '14': {
        'model': 'ZX Spectrum Nordisk',
        'year': '1984',
        'type': 'Licensed',
        'country': 'Sweden',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-beckman.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Beckman Innovation AB',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '3': {
        'model': 'ZX Spectrum +',
        'year': '1986',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': 'tapeloaders\/tape_128.szx',
        'tape_usr0': 'tapeloaders\/tape_128_usr0.szx',
        'rom0': 'roms\/128-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sinclair',
        'style': 'spectrum128p',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '4': {
        'model': 'ZX Spectrum +',
        'year': '1985',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-spanish-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-spanish-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sinclair',
        'style': 'spectrum128p',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '5': {
        'model': 'ZX Spectrum +2',
        'year': '1986',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': 'tapeloaders\/tape_plus2.szx',
        'tape_usr0': 'tapeloaders\/tape_plus2.szx',
        'rom0': 'roms\/128-plus2-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '6': {
        'model': 'ZX Spectrum +2',
        'year': '1986',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': 'tapeloaders\/tape_plus2.szx',
        'tape_usr0': 'tapeloaders\/tape_plus2.szx',
        'rom0': 'roms\/128-plus2es-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2es-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '7': {
        'model': 'ZX Spectrum +2',
        'year': '1986',
        'type': 'Original',
        'country': 'UK',
        'lang': 'FR',
        'memory': '128',
        'tape': 'tapeloaders\/tape_plus2.szx',
        'tape_usr0': 'tapeloaders\/tape_plus2.szx',
        'rom0': 'roms\/128-plus2fr-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2fr-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '8': {
        'model': 'Pentagon 128',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '128',
        'tape': 'tapeloaders\/tape_pentagon.szx',
        'tape_usr0': 'tapeloaders\/tape_pentagon_usr0.szx',
        'rom0': 'roms\/128-pentagon-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-1.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-pentagon-trdos.rom',
        'rom2_page': 14,
        'status': 1,
        'manufacturer': 'Unknown',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '19': {
        'model': 'Pentagon 48',
        'year': '198X',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-pentagon.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Unknown',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ARUS AR-CS 010',
        'family': 'ZX Spectrum'
      },
      '9': {
        'model': 'TC2048',
        'year': '1984',
        'type': 'Unlicensed',
        'country': 'Portugal',
        'lang': 'EN',
        'memory': '16',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tc2048.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Timex Corp.',
        'style': 'tc2048',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '10': {
        'model': 'TC2068 / TS2068',
        'year': '1983',
        'type': 'Licensed',
        'country': 'Portugal',
        'lang': 'EN',
        'memory': '48',
        'tape': 'tapeloaders\/tape_ts2068.szx',
        'tape_usr0': 'tapeloaders\/tape_ts2068.szx',
        'rom0': 'roms\/48-ts2068-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/48-ts2068-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Timex Corp. / Sinclair',
        'style': 'tc2068',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Load ROM KO? check memory layout',
        'family': 'ZX Spectrum'
      },
      '11': {
        'model': 'Inves Spectrum +',
        'year': '1986',
        'type': 'Licensed',
        'country': 'Spain',
        'lang': 'ES',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-inves.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Investronica S.A.',
        'style': 'inves',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '12': {
        'model': 'TK90X',
        'year': '1985',
        'type': 'Unlicensed',
        'country': 'Brazil',
        'lang': 'PT',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tk90xpt.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Microdigital',
        'style': 'microdigitaltk90x',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '16': {
        'model': 'TK90X',
        'year': '1985',
        'type': 'Unlicensed',
        'country': 'Brazil',
        'lang': 'PT/ES',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tk90xptes.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Microdigital',
        'style': 'microdigitaltk90x',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '17': {
        'model': 'TK90X',
        'year': '1985',
        'type': 'Unlicensed',
        'country': 'Brazil',
        'lang': 'ES',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tk90xes.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Microdigital',
        'style': 'microdigitaltk90x',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '13': {
        'model': 'TK95',
        'year': '1986',
        'type': 'Unlicensed',
        'country': 'Brazil',
        'lang': 'PT',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tk95pt.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Microdigital',
        'style': 'microdigitaltk95',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '18': {
        'model': 'TK95',
        'year': '1986',
        'type': 'Unlicensed',
        'country': 'Brazil',
        'lang': 'PT',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-tk95es.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Microdigital',
        'style': 'microdigitaltk95',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '24': {
        'model': 'Didaktik Gama 87',
        'year': '1987',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '80',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-dgama87.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '25': {
        'model': 'Didaktik Gama 88',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '80',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-dgama88.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '15': {
        'model': 'Didaktik Gama 89',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '80',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-dgama89.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '20': {
        'model': 'Sintez 48',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-sintez.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Signal',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '21': {
        'model': 'Sintez M',
        'year': '1990',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-sintezm.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Signal',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '22': {
        'model': 'Byte',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-byte.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Brest EM Plant',
        'style': 'byte',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '23': {
        'model': 'Kvorum',
        'year': '1993',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-quorum.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Kvorum',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load OK, but no keyboard',
        'family': 'ZX Spectrum'
      },
      '26': {
        'model': 'Delta-S 89',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-deltas.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Kursk',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Load ROM KO? check memory layout',
        'family': 'ZX Spectrum'
      },
      '27': {
        'model': 'Delta-S 90',
        'year': '1990',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-delta90.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Kursk',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '28': {
        'model': 'Delta-S 91',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-delta91.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Kursk',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '29': {
        'model': 'Dubna 48',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-dubna.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Dubna',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Tape loading not working',
        'family': 'ZX Spectrum'
      },
      '30': {
        'model': 'Orel BK-08 v2',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-orelbk08v2.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Dniprovsky',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Keyboard mapping problems',
        'family': 'ZX Spectrum'
      },
      '31': {
        'model': 'Fanny Leningrad',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-fanny.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Piter Ltd',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '32': {
        'model': 'Elektronika VI-201',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-parus.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Parus',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '33': {
        'model': 'Vesta IK-30',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-vesta.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Signal',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '34': {
        'model': 'Erudit 002',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-erudit.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Etalon',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '35': {
        'model': 'ZX Spectrum +2A V4.0',
        'year': '1988',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3env4-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2a3env4-1.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-plus2a3env4-2.rom',
        'rom2_page': 10,
        'rom3': 'roms\/128-plus2a3env4-3.rom',
        'rom3_page': 11,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2a',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '36': {
        'model': 'ZX Spectrum +2A V4.1',
        'year': '1988',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3env41.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'rom3': false,
        'rom3_page': false,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2a',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '37': {
        'model': 'ZX Spectrum +2A V4.0',
        'year': '1988',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3esv4-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2a3esv4-1.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-plus2a3esv4-2.rom',
        'rom2_page': 10,
        'rom2': 'roms\/128-plus2a3esv4-3.rom',
        'rom2_page': 11,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2a',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '38': {
        'model': 'ZX Spectrum +2A V4.1',
        'year': '1988',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3esv41.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'rom3': false,
        'rom3_page': false,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2a',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '39': {
        'model': 'ZX Spectrum +3 V4.0',
        'year': '1987',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3env4-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2a3env4-1.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-plus2a3env4-2.rom',
        'rom2_page': 10,
        'rom3': 'roms\/128-plus2a3env4-3.rom',
        'rom3_page': 11,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p3',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '40': {
        'model': 'ZX Spectrum +3 V4.1',
        'year': '1987',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3env41.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'rom3': false,
        'rom3_page': false,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p3',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '41': {
        'model': 'ZX Spectrum +3 V4.0',
        'year': '1987',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3esv4-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2a3esv4-1.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-plus2a3esv4-2.rom',
        'rom2_page': 10,
        'rom2': 'roms\/128-plus2a3esv4-3.rom',
        'rom2_page': 11,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p3',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '42': {
        'model': 'ZX Spectrum +3 V4.1',
        'year': '1987',
        'type': 'Original',
        'country': 'UK',
        'lang': 'ES',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2a3esv41.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'rom3': false,
        'rom3_page': false,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p3',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '43': {
        'model': 'ZX Spectrum +2B',
        'year': '1988',
        'type': 'Original',
        'country': 'UK',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-plus2b-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-plus2b-2.rom',
        'rom1_page': 9,
        'rom2': 'roms\/128-plus2b-a.rom',
        'rom2_page': 10,
        'rom3': 'roms\/128-plus2b-b.rom',
        'rom3_page': 11,
        'status': 0,
        'manufacturer': 'Amstrad / Sinclair',
        'style': 'spectrum128p2a',
        'worker': 'zxspectrum-worker.js',
        'comments': 'TO DO',
        'family': 'ZX Spectrum'
      },
      '44': {
        'model': 'ZX Spectrum Arabic v1',
        'year': '1987',
        'type': 'Licensed',
        'country': 'Egypt',
        'lang': 'AR',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-arabicv1.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'status': 1,
        'manufacturer': 'Sinclair Egypt',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '45': {
        'model': 'ZX Spectrum Arabic v2',
        'year': '1987',
        'type': 'Licensed',
        'country': 'Egypt',
        'lang': 'AR',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-arabicv2.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'status': 1,
        'manufacturer': 'Sinclair Egypt',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '46': {
        'model': 'ZX Spectrum Arabic v3.1',
        'year': '1988',
        'type': 'Licensed',
        'country': 'Egypt',
        'lang': 'AR',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-arabicv31.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': false,
        'rom2': false,
        'rom2_page': false,
        'status': 1,
        'manufacturer': 'Sinclair Egypt',
        'style': 'spectrum48',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '47': {
        'model': 'Didaktik M 91',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-didakm91.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO? check memory layout',
        'family': 'ZX Spectrum'
      },
      '48': {
        'model': 'Didaktik M 92',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-didakm92.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO? check memory layout',
        'family': 'ZX Spectrum'
      },
      '49': {
        'model': 'Didaktik M 93',
        'year': '1993',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-didakm93.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO? check memory layout',
        'family': 'ZX Spectrum'
      },
      '50': {
        'model': 'Didaktik Kompakt 128',
        'year': '1993',
        'type': 'Unlicensed',
        'country': 'Czechoslovakia',
        'lang': 'EN',
        'memory': '128',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/128-dkompakt-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/128-dkompakt-1.rom',
        'rom1_page': 9,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Didaktik Skalica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Disk not yet emulated!',
        'family': 'ZX Spectrum'
      },
      '51': {
        'model': 'Hobbit',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hobbit.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Intercompex',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '52': {
        'model': 'Magic 05',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-magic05.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Axon',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Keyboard KO',
        'family': 'ZX Spectrum'
      },
      '53': {
        'model': 'Magic 6.5',
        'year': '1994',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-magic065.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2, // Everything looks OK, but no keyboard !!!
        'manufacturer': 'Axon',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Keyboard KO',
        'family': 'ZX Spectrum'
      },
      '54': {
        'model': 'Baltic',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-baltic.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sonet',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '55': {
        'model': 'Baltic 1.2',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-baltic12.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Sonet',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '56': {
        'model': 'Baltic Turbo',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'EN',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-balticturbo.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Sonet',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO! Check memory layout',
        'family': 'ZX Spectrum'
      },
      '57': {
        'model': 'Baltic',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'URSS',
        'lang': 'RU',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-balticru.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Sonet',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO! Check memory layout',
        'family': 'ZX Spectrum'
      },
      '58': {
        'model': 'HC 85',
        'year': '1985',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc85.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '59': {
        'model': 'HC 88',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc88filled.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'ROM Load KO! Check rom and memory layout',
        'family': 'ZX Spectrum'
      },
      '60': {
        'model': 'HC 90',
        'year': '1990',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc90.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '61': {
        'model': 'HC 91',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc91.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '62': {
        'model': 'HC 2000 v1',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc2000v1-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/48-hc2000v1-1.rom',
        'rom1_page': 13,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '63': {
        'model': 'HC 2000 v2',
        'year': '1992',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc2000v2-0.rom',
        'rom0_page': 8,
        'rom1': 'roms\/48-hc2000v2-1.rom',
        'rom1_page': 13,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Disk not yet emulated',
        'family': 'ZX Spectrum'
      },
      '64': {
        'model': 'HC 91+',
        'year': '1991',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-hc128.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Ice Felix',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Disk not yet emulated',
        'family': 'ZX Spectrum'
      },
      '65': {
        'model': 'CIP-01',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-cip01.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'Intreprindera Electronica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Basic Tape boot not yet tested',
        'family': 'ZX Spectrum'
      },
      '66': {
        'model': 'CIP-03',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-cip03.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Intreprindera Electronica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '67': {
        'model': 'JET',
        'year': '1989',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '48',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-jet.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 1,
        'manufacturer': 'Electromagnetica',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': '',
        'family': 'ZX Spectrum'
      },
      '68': {
        'model': 'Cobra + Opus OS Boot',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '64',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/64-cobraopus.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 2,
        'manufacturer': 'ITCI',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Disk not yet emulated',
        'family': 'ZX Spectrum'
      },
      '69': {
        'model': 'Cobra',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '64',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/64-cobra.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'ITCI',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Not Booting',
        'family': 'ZX Spectrum'
      },
      '70': {
        'model': 'Cobra 80k',
        'year': '1988',
        'type': 'Unlicensed',
        'country': 'Romania',
        'lang': 'RO',
        'memory': '80',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/80-cobra.rom',
        'rom0_page': 8,
        'rom1': false,
        'rom1_page': null,
        'rom2': false,
        'rom2_page': null,
        'status': 0,
        'manufacturer': 'ITCI',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Not Booting',
        'family': 'ZX Spectrum'
      },
      '71': {
        'model': 'Elwro 800-3 Junior',
        'year': '1985',
        'type': 'Unlicensed',
        'country': 'Poland',
        'lang': 'PO',
        'memory': '64',
        'tape': false,
        'tape_usr0': false,
        'rom0': 'roms\/48-elwro-boot03.rom',
        'rom0_page': 8,
        'rom1': 'roms\/48-elwro-bas03.rom',
        'rom1_page': 9,
        'rom2': 'roms\/48-elwro-bas13.rom',
        'rom2_page': 10,
        'status': 0,
        'manufacturer': 'Poznan Technical University',
        'style': 'clone',
        'worker': 'zxspectrum-worker.js',
        'comments': 'Load ROM KO? check memory layout',
        'family': 'ZX Spectrum'
      }
    };
  }
  getList() {
    return this.machineList;
  }
  getOrderedList() {
    let machinesArray = [];
    const machineList = this.machineList;
    Object.keys(machineList).forEach(function (item) {
      let tempObject = machineList[item];
      tempObject['id'] = item;
      machinesArray.push(tempObject);
    });
    machinesArray.sort(function (a, b) {
      if (a.model < b.model) {
        return -1;
      }
      if (a.model > b.model) {
        return 1;
      }
      return 0;
    });
    return machinesArray;
  }
  getStyles() {
    let stylesArray = [];
    const machineList = this.machineList;
    Object.keys(machineList).forEach(function (item) {
      stylesArray.push(machineList[item]['style']);
    });
    return stylesArray.filter((value, index) => stylesArray.indexOf(value) === index);
  }
  getRomsByMachine(type) {
    const machineList = this.machineList;
    return {
      'rom0': machineList[type]['rom0'],
      'rom0_page': machineList[type]['rom0_page'],
      'rom1': machineList[type]['rom1'],
      'rom1_page': machineList[type]['rom1_page'],
      'rom2': machineList[type]['rom2'],
      'rom2_page': machineList[type]['rom2_page'],
    };
  }
}
